DROP TABLE IF EXISTS filmek;
DROP TABLE IF EXISTS kategoria;
DROP TABLE IF EXISTS sorozatok;
DROP TABLE IF EXISTS resz;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS saw;


CREATE TABLE filmek (
id INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
cim VARCHAR(255) NOT NULL,
hossz INT NOT NULL,
kategoria INT NOT NULL,
borito VARCHAR(255) NOT NULL);

CREATE TABLE kategoria (
id INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
name VARCHAR(255) NOT NULL);

CREATE TABLE sorozatok (
id INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
evad INT NOT NULL,
resz INT NOT NULL,
cim VARCHAR(255) NOT NULL,
kategoria INT NOT NULL,
borito VARCHAR(255) NOT NULL);

CREATE TABLE resz (
id INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
evadSzam INT NOT NULL,
reszSzam INT NOT NULL,
cim VARCHAR(255) NOT NULL,
hossz INT NOT NULL,
sorozatid INT NOT NULL);

CREATE TABLE users (
uid INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
username VARCHAR(45) NOT NULL,
password VARCHAR(45) NOT NULL,
email VARCHAR(45) NOT NULL,
permission INT NOT NULL,
profilepic INT NOT NULL DEFAULT 1);

CREATE TABLE saw (
id INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
uid INT NOT NULL,
eid INT NOT NULL);

ALTER TABLE filmek ADD CONSTRAINT filmek_kategoria_kategoria_id FOREIGN KEY (kategoria) REFERENCES kategoria(id);
ALTER TABLE sorozatok ADD CONSTRAINT sorozatok_kategoria_kategoria_id FOREIGN KEY (kategoria) REFERENCES kategoria(id);
ALTER TABLE resz ADD CONSTRAINT resz_evadSzam_sorozatok_id FOREIGN KEY (evadSzam) REFERENCES sorozatok(id);
ALTER TABLE resz ADD CONSTRAINT resz_sorozatid_sorozatok_id FOREIGN KEY (sorozatid) REFERENCES sorozatok(id);
ALTER TABLE saw ADD CONSTRAINT saw_uid_users_uid FOREIGN KEY (uid) REFERENCES users(uid);
ALTER TABLE saw ADD CONSTRAINT saw_eid_filmek_id FOREIGN KEY (eid) REFERENCES filmek(id);
